{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

".oh-my-zsh":
  type: archive
  {{ $omzRevision := includeTemplate "get-github-head-revision" (list "ohmyzsh/ohmyzsh" $cache) }}
  url: "https://github.com/ohmyzsh/ohmyzsh/archive/{{ $omzRevision }}.tar.gz"
  stripComponents: 1
  # waiting for https://github.com/twpayne/chezmoi/issues/1614#issuecomment-966524408
  # exact: true

".oh-my-zsh/custom/themes/powerlevel10k":
  type: archive
  {{ $p10kRevision := includeTemplate "get-github-head-revision" (list "romkatv/powerlevel10k" $cache) }}
  url: "https://github.com/romkatv/powerlevel10k/archive/{{ $p10kRevision }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-syntax-highlighting":
  type: archive
  {{ $zshSyntaxHighlightingRevision := includeTemplate "get-github-head-revision" (list "zsh-users/zsh-syntax-highlighting" $cache) }}
  url: "https://github.com/zsh-users/zsh-syntax-highlighting/archive/{{ $zshSyntaxHighlightingRevision }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-autosuggestions":
  type: archive
  {{ $zshAutoSuggestionsRevision := includeTemplate "get-github-head-revision" (list "zsh-users/zsh-autosuggestions" $cache) }}
  url: "https://github.com/zsh-users/zsh-autosuggestions/archive/{{ $zshAutoSuggestionsRevision }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-completions":
  type: archive
  {{ $zshCompletionsRevision := includeTemplate "get-github-head-revision" (list "zsh-users/zsh-completions" $cache) }}
  url: "https://github.com/zsh-users/zsh-completions/archive/{{ $zshCompletionsRevision }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-tmux":
  type: git-repo
  {{ $ohMyTmuxRevision := includeTemplate "get-github-head-revision" (list "gpakosz/.tmux" $cache) }}
  url: "https://github.com/gpakosz/.tmux.git"
  clone.args: "--single-branch"

".config/gitalias/gitalias.txt":
  type: file
  {{ $gitaliasRevision := includeTemplate "get-github-head-revision" (list "GitAlias/gitalias" $cache) }}
  url: "https://github.com/GitAlias/gitalias/raw/{{ $gitaliasRevision }}/gitalias.txt"

{{ if not .is_devcontainer | or (.is_devcontainer | and (not (lookPath "retry"))) -}}
".local/bin/retry":
  type: file
  {{ $retryVersion := includeTemplate "get-github-latest-version" (list "kadwanev/retry" $cache) }}
  url: "https://github.com/kadwanev/retry/raw/{{ $retryVersion }}/retry"
  executable: true
{{- end }}

{{ if not .is_devcontainer | or (.is_devcontainer | and (not (lookPath "direnv"))) -}}
".local/bin/direnv":
  type: file
  {{ $direnvVersion := includeTemplate "get-github-latest-version" (list "direnv/direnv" $cache) }}
  url: "https://github.com/direnv/direnv/releases/download/v{{ $direnvVersion }}/direnv.linux-{{ .chezmoi.arch }}"
  executable: true
{{- end }}

{{ if not .is_devcontainer | or (.is_devcontainer | and (not (lookPath "pkgx")) | and (ne .chezmoi.osRelease.id "alpine")) -}}
".local/bin/pkgx":
  type: archive-file
  {{ $pkgxVersion := includeTemplate "get-github-latest-version" (list "pkgxdev/pkgx" $cache) }}
  url: "https://github.com/pkgxdev/pkgx/releases/download/v{{ $pkgxVersion }}/pkgx-{{ $pkgxVersion }}+linux+{{ .uname_arch | replace "_" "-" }}.tar.xz"
  path: pkgx
{{- end }}

{{ if not .is_devcontainer -}}
".local/bin/pipx":
  type: file
  {{ $pipxVersion := includeTemplate "get-github-latest-version" (list "pypa/pipx" $cache) }}
  url: "https://github.com/pypa/pipx/releases/download/{{ $pipxVersion }}/pipx.pyz"
  executable: true

".volta/bin":
  type: archive
  {{ $voltaVersion := includeTemplate "get-github-latest-version" (list "volta-cli/volta" $cache) }}
  url: "https://github.com/volta-cli/volta/releases/download/v{{ $voltaVersion }}/volta-{{ $voltaVersion }}-linux.tar.gz"

".deno/bin/deno":
  type: archive-file
  {{ $denoVersion := includeTemplate "get-github-latest-version" (list "denoland/deno" $cache) }}
  url: "https://github.com/denoland/deno/releases/download/v{{ $denoVersion }}/deno-{{ .uname_arch }}-unknown-linux-gnu.zip"
  path: deno

"{{ joinPath .fontsDir .terminalFont.fileName }}":
  type: file
  {{ $nerdFontsVersion := includeTemplate "get-github-latest-version" (list "ryanoasis/nerd-fonts" $cache) }}
  url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/v{{ $nerdFontsVersion }}/patched-fonts/FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf"

{{    if .is_wsl -}}
{{    $externalScriptsDir := includeTemplate "get-external-scripts-dir" . }}
"{{ $externalScriptsDir }}/Install-Font.ps1":
  type: file
  {{ $psWinGlueRevision := includeTemplate "get-github-head-revision" (list "ralish/PSWinGlue" $cache) }}
  url: "https://raw.githubusercontent.com/ralish/PSWinGlue/{{ $psWinGlueRevision }}/Scripts/Install-Font.ps1"

"{{ $externalScriptsDir }}/Uninstall-Font.ps1":
  type: file
  url: "https://raw.githubusercontent.com/ralish/PSWinGlue/{{ $psWinGlueRevision }}/Scripts/Uninstall-Font.ps1"
{{-   end }}

{{- template "save-versions-and-revisions-cache" $cache -}}

{{- end -}}
