#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=test-helpers.sh
. "$(dirname "${BASH_SOURCE[0]}")/test-helpers.sh"
test_setup 1 "$@"
script_path="$1"

mkdir -p \
  "${test_root}/bin" \
  "${test_root}/chrome/Default" \
  "${test_root}/chrome/Profile 1" \
  "${test_root}/chrome/System Profile" \
  "${test_root}/external"

cat >"${test_root}/bin/google-chrome" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "${test_root}/bin/google-chrome"

cat >"${test_root}/bin/sudo" <<'EOF'
#!/usr/bin/env bash
if [[ "${1:-}" == "-n" && "${2:-}" == "-v" ]]; then
  exit 0
fi
exec "$@"
EOF
chmod +x "${test_root}/bin/sudo"

cat >"${test_root}/bin/ps" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "${test_root}/bin/ps"

cat >"${test_root}/chrome/Default/Preferences" <<'EOF'
{"profile":{"name":"Default"},"extensions":{"theme":{"system_theme":1}},"unrelated":{"keep":true}}
EOF
cat >"${test_root}/chrome/Profile 1/Preferences" <<'EOF'
{"profile":{"name":"Work"},"extensions":{"theme":{"id":"autogenerated_theme_id","system_theme":0}},"unrelated":{"keep":true}}
EOF
cat >"${test_root}/chrome/System Profile/Preferences" <<'EOF'
{"profile":{"name":"System"}}
EOF
for backup_number in 1 2 3 4; do
  printf 'old backup %s\n' "${backup_number}" > "${test_root}/chrome/Default/Preferences.chezmoi-backup.2026010100000${backup_number}"
done

PATH="${test_root}/bin:${PATH}" \
  CHROME_CONFIG_DIR="${test_root}/chrome" \
  CHROME_EXTERNAL_EXTENSIONS_DIR="${test_root}/external" \
  bash "${script_path}"

theme_id="gfapcejdoghpoidkfodoiiffaaibpaem"
python3 - "${test_root}" "${theme_id}" <<'PY'
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
theme_id = sys.argv[2]

metadata = json.loads((root / "external" / f"{theme_id}.json").read_text())
assert metadata == {"external_update_url": "https://clients2.google.com/service/update2/crx"}

for profile in ("Default", "Profile 1"):
    preferences = json.loads((root / "chrome" / profile / "Preferences").read_text())
    assert preferences["extensions"]["theme"] == {"system_theme": 0, "id": theme_id}
    assert preferences["unrelated"] == {"keep": True}

system_preferences = json.loads((root / "chrome/System Profile/Preferences").read_text())
assert system_preferences == {"profile": {"name": "System"}}
assert len(list((root / "chrome/Default").glob("Preferences.chezmoi-backup.*"))) == 3
assert len(list((root / "chrome/Profile 1").glob("Preferences.chezmoi-backup.*"))) == 1
PY

cat >"${test_root}/bin/sudo" <<'EOF'
#!/usr/bin/env bash
if [[ "${1:-}" == "-n" && "${2:-}" == "-v" ]]; then
  exit 1
fi
exec "$@"
EOF
chmod +x "${test_root}/bin/sudo"
if PATH="${test_root}/bin:${PATH}" \
  CHROME_CONFIG_DIR="${test_root}/chrome" \
  CHROME_EXTERNAL_EXTENSIONS_DIR="${test_root}/external" \
  bash "${script_path}" >"${test_root}/sudo-failure.out" 2>&1; then
  printf 'error: Chrome hook accepted missing cached sudo credentials\n' >&2
  exit 1
fi
grep -Fq "run 'sudo -v' in a visible terminal" "${test_root}/sudo-failure.out"

printf 'Google Chrome Dracula theme checks passed\n'
