#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=fixture.sh
. "$(dirname -- "${BASH_SOURCE[0]}")/fixture.sh"
test_setup "$@"
script_path="$(test_render_template 'home/.chezmoiscripts/run_always_after_24-configure-google-chrome-theme.sh.tmpl')"

mkdir -p \
  "${test_root}/chrome/Default" \
  "${test_root}/chrome/Profile 1" \
  "${test_root}/chrome/System Profile" \
  "${test_root}/external"

test_stub_command google-chrome
# No Chrome process is running.
test_stub_command ps

# Cached sudo credentials are available, so `sudo -n -v` succeeds.
grant_sudo() {
  test_stub_command sudo - <<'STUB'
if [[ "${1:-}" == '-n' && "${2:-}" == '-v' ]]; then
  exit 0
fi
exec "$@"
STUB
}

refuse_sudo() {
  test_stub_command sudo - <<'STUB'
if [[ "${1:-}" == '-n' && "${2:-}" == '-v' ]]; then
  exit 1
fi
exec "$@"
STUB
}

cat >"${test_root}/chrome/Default/Preferences" <<'EOF'
{"profile":{"name":"Default"},"extensions":{"theme":{"system_theme":1}},"unrelated":{"keep":true}}
EOF
cat >"${test_root}/chrome/Profile 1/Preferences" <<'EOF'
{"profile":{"name":"Work"},"extensions":{"theme":{"id":"autogenerated_theme_id","system_theme":0}},"unrelated":{"keep":true}}
EOF
cat >"${test_root}/chrome/System Profile/Preferences" <<'EOF'
{"profile":{"name":"System"}}
EOF
for backup_number in 1 2 3 4; do
  printf 'old backup %s\n' "${backup_number}" >"${test_root}/chrome/Default/Preferences.chezmoi-backup.2026010100000${backup_number}"
done

configure_theme() {
  CHROME_CONFIG_DIR="${test_root}/chrome" \
    CHROME_EXTERNAL_EXTENSIONS_DIR="${test_root}/external" \
    test_run_script "${script_path}"
}

grant_sudo
configure_theme

theme_id="gfapcejdoghpoidkfodoiiffaaibpaem"
python3 - "${test_root}" "${theme_id}" <<'PY'
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
theme_id = sys.argv[2]

metadata = json.loads((root / "external" / f"{theme_id}.json").read_text())
assert metadata == {"external_update_url": "https://clients2.google.com/service/update2/crx"}

for profile in ("Default", "Profile 1"):
    preferences = json.loads((root / "chrome" / profile / "Preferences").read_text())
    assert preferences["extensions"]["theme"] == {"system_theme": 0, "id": theme_id}
    assert preferences["unrelated"] == {"keep": True}

system_preferences = json.loads((root / "chrome/System Profile/Preferences").read_text())
assert system_preferences == {"profile": {"name": "System"}}
assert len(list((root / "chrome/Default").glob("Preferences.chezmoi-backup.*"))) == 3
assert len(list((root / "chrome/Profile 1").glob("Preferences.chezmoi-backup.*"))) == 1
PY

# Without cached credentials the hook must refuse rather than block on a prompt.
refuse_sudo
if configure_theme >"${test_root}/sudo-failure.out" 2>&1; then
  printf 'error: Chrome hook accepted missing cached sudo credentials\n' >&2
  exit 1
fi
grep -Fq "run 'sudo -v' in a visible terminal" "${test_root}/sudo-failure.out"

printf 'Google Chrome Dracula theme checks passed\n'
