{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

"usr/share/keyrings/githubcli-archive-keyring.gpg":
  type: file
  url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]
    
"usr/share/keyrings/docker-archive-keyring.gpg":
  type: file
  url: "https://download.docker.com/linux/{{ .chezmoi.osRelease.id }}/gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/git-core-ppa-archive-keyring.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF911AB184317630C59970973E363C90F8F1B6217"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ if .is_wsl }}
"usr/share/keyrings/wslu-ppa-archive-keyring.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x254F460F2970E18123046570C1D0E7E6AB4095D6"
  filter:
    command: gpg
    args: ["--dearmor"]
{{ end }}

{{ if .is_gnome }}
"usr/share/keyrings/shiftkey-archive-keyring.gpg":
  type: file
  url: "https://apt.packages.shiftkey.dev/gpg.key"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/1password-archive-keyring.gpg":
  type: file
  url: "https://downloads.1password.com/linux/keys/1password.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/spotify-archive-keyring.gpg":
  type: file
  url: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/vscode-archive-keyring.gpg":
  type: file
  url: "https://packages.microsoft.com/keys/microsoft.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/google-chrome-archive-keyring.gpg":
  type: file
  url: "https://dl.google.com/linux/linux_signing_key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]
{{ end }}

"usr/local/bin/docker-compose":
  type: file
  {{ $composeVersion := includeTemplate "get-github-latest-version" (list "docker/compose-switch" $cache) }}
  url: "https://github.com/docker/compose-switch/releases/download/v{{ $composeVersion }}/docker-compose-linux-{{ .chezmoi.arch }}"
  executable: true

"usr/local/bin/cursor.appimage":
  type: file
  url: "https://downloader.cursor.sh/linux/appImage/x64"
  executable: true

"usr/local/cursor/cursor-dark.avif":
  type: file
  url: "https://www.cursor.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-dark.c2eae9ea.png&w=96&q=96"

"usr/local/bin/git-lfs":
  type: archive-file
  {{ $gitLfsVersion := includeTemplate "get-github-latest-version" (list "git-lfs/git-lfs" $cache) }}
  url: "https://github.com/git-lfs/git-lfs/releases/download/v{{ $gitLfsVersion }}/git-lfs-linux-{{ .chezmoi.arch }}-v{{ $gitLfsVersion }}.tar.gz"
  stripComponents: 1
  path: git-lfs

{{ $dockerCredVersion := includeTemplate "get-github-latest-version" (list "docker/docker-credential-helpers" $cache) }}
{{ $gcmVersion := includeTemplate "get-github-latest-version" (list "GitCredentialManager/git-credential-manager" $cache) }}
{{ if .is_wsl }}
"usr/bin/docker-credential-wincred.exe":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ $dockerCredVersion }}/docker-credential-wincred-v{{ $dockerCredVersion }}.windows-{{ .chezmoi.arch }}.exe"
  executable: true

"usr/local/share/gcm":
  type: archive
  url: "https://github.com/GitCredentialManager/git-credential-manager/releases/download/v{{ $gcmVersion }}/gcm-win-x86-{{ $gcmVersion }}.zip"
  exact: true
{{ else }}
"usr/local/share/gcm":
  type: archive
  url: "https://github.com/GitCredentialManager/git-credential-manager/releases/download/v{{ $gcmVersion }}/gcm-linux_{{ .chezmoi.arch }}.{{ $gcmVersion }}.tar.gz"
  exact: true

{{   if .is_gnome }}
"usr/bin/docker-credential-secretservice":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ $dockerCredVersion }}/docker-credential-secretservice-v{{ $dockerCredVersion }}.linux-{{ .chezmoi.arch }}"
  executable: true
{{   end }}
{{ end }}

{{ template "save-versions-and-revisions-cache" $cache -}}
